config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from drf_spectacular.views import SpectacularAPIView
from drf_spectacular.views import SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", include("task_overflow.pages.urls", namespace="pages")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("task_overflow.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path(
        "characters/", include("task_overflow.characters.urls", namespace="characters")
    ),
    path(
        "encounters/", include("task_overflow.encounters.urls", namespace="encounters")
    ),
    path(
        "hx/",
        include("task_overflow.hx.urls", namespace="hx"),
    ),
    path("items/", include("task_overflow.items.urls", namespace="items")),
    path(
        "tasks/",
        include("task_overflow.tasks.urls", namespace="tasks"),
    ),
    path(
        "trackers/",
        include("task_overflow.trackers.urls", namespace="trackers"),
    ),
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("api/auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

task_overflow/hx/urls.py
from django.urls import path

from .views import empty_view

app_name = "hx"
urlpatterns = [
    path("empty/", empty_view, name="empty"),
]

task_overflow/items/urls.py
from django.urls import path

from .views import character_item_create_view
from .views import character_item_equip_melee_weapon_view
from .views import character_item_use_view

app_name = "items"
urlpatterns = [
    path(
        "<int:character>/character-items/<int:item>/~create/",
        view=character_item_create_view,
        name="character-item-create",
    ),
    path(
        "character-items/melee-weapons/<int:pk>/~equip/",
        view=character_item_equip_melee_weapon_view,
        name="character-melee-weapon-equip",
    ),
    path(
        "character-items/<int:pk>/~use/",
        view=character_item_use_view,
        name="character-item-use",
    ),
]

task_overflow/pages/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import home_view

app_name = "pages"
urlpatterns = [
    path("", home_view, name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
]

task_overflow/users/urls.py
from django.urls import path

from .views import user_detail_view
from .views import user_redirect_view
from .views import user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<int:pk>/", view=user_detail_view, name="detail"),
]

task_overflow/hx/models.py
# Create your models here.

task_overflow/tasks/forms.py
from typing import TYPE_CHECKING

from django import forms

from .models import Habit
from .models import Todo

if TYPE_CHECKING:
    from task_overflow.users.models import User


class DatePickerInput(forms.DateInput):
    input_type = "date"


class HabitForm(forms.ModelForm):
    def __init__(self, user: "User", *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.fields["category"].queryset = user.categories()

    class Meta:
        model = Habit
        fields = [
            "category",
            "name",
            "experience_points",
        ]


class TodoForm(forms.ModelForm):
    def __init__(self, user: "User", *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.fields["category"].queryset = user.categories()

    class Meta:
        model = Todo
        fields = [
            "category",
            "name",
            "experience_points",
            "due_date",
            "recurring_schedule",
            "notes",
        ]
        widgets = {
            "due_date": DatePickerInput(),
        }

task_overflow/trackers/forms.py
from django import forms

from .models import Adjustment


class NegativeAdjustmentForm(forms.ModelForm):
    def clean_value(self):
        return self.cleaned_data["value"] * -1

    class Meta:
        model = Adjustment
        fields = ["value"]

task_overflow/characters/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.urls import reverse
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView

from task_overflow.hx.decorators import hx_login_required
from task_overflow.hx.mixins import HXLoginRequiredMixin
from task_overflow.hx.utils import htmx_redirect
from task_overflow.items.models import Item
from task_overflow.utils import empty_response

from .models import Character
from .models import CharacterLevelUp
from .models import CharacterMessage


def display_message(request, message: "CharacterMessage") -> None:
    messages.add_message(
        request,
        level=message.level,
        message=message.text,
    )
    message.status = CharacterMessage.Status.VIEWED
    message.save()


class CharacterCreateView(LoginRequiredMixin, CreateView):
    model = Character
    fields = [
        "name",
        "avatar",
    ]
    success_message = "Character created"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


character_create_view = CharacterCreateView.as_view()


class CharacterDetailView(LoginRequiredMixin, DetailView):
    model = Character

    def get_queryset(self):
        return self.request.user.character_set.all()

    def get_object(self, *args, **kwargs) -> "Character":
        obj = super().get_object(*args, **kwargs)
        for death in obj.pending_deaths():
            death.die()
        for message in obj.ordered_pending_messages():
            display_message(self.request, message=message)
        return obj

    def get_context_data(self, *args, **kwargs) -> dict:
        context = super().get_context_data(*args, **kwargs)
        context["items_for_sale"] = Item.objects.for_sale()
        return context


character_detail_view = CharacterDetailView.as_view()


@hx_login_required
def character_hx_fetch_messages_view(request, pk: int):
    character = get_object_or_404(request.user.character_set, pk=pk)
    for message in character.ordered_pending_messages():
        display_message(request, message=message)
    return render(request, "includes/messages.html")


@hx_login_required
def character_hx_check_for_active_encounter_view(request, pk: int, force: int = 0):
    force = force == 1
    character = get_object_or_404(request.user.character_set, pk=pk)
    active_encounter = character.get_or_create_active_encounter(force=force)
    if active_encounter:
        messages.add_message(
            request,
            message="You were attacked!",
            level=messages.ERROR,
        )
        return htmx_redirect(
            for_path=reverse(
                "encounters:detail",
                kwargs={
                    "pk": active_encounter.pk,
                },
            ),
        )
    return empty_response()


class CharacterHXFetchDetailsView(HXLoginRequiredMixin, DetailView):
    model = Character
    template_name = "characters/includes/character_details.html"

    def get_queryset(self):
        return self.request.user.character_set.all()

    def get_object(self, *args, **kwargs) -> "Character":
        obj = super().get_object(*args, **kwargs)
        for death in obj.pending_deaths():
            death.die()
        return obj


character_hx_fetch_details_view = CharacterHXFetchDetailsView.as_view()


class CharacterUpdateView(LoginRequiredMixin, UpdateView):
    model = Character
    fields = [
        "name",
        "avatar",
    ]
    success_message = "Character updated"

    def get_queryset(self):
        return self.request.user.character_set.all()


character_update_view = CharacterUpdateView.as_view()


class CharacterLevelUpCompleteView(LoginRequiredMixin, UpdateView):
    model = CharacterLevelUp
    fields = [
        "hit_points",
        "strength_points",
        "dexterity_points",
        "initiative_points",
    ]

    @property
    def character(self) -> "Character":
        return self.object.character

    def get_queryset(self):
        return self.request.user.character_level_ups().filter(
            status=CharacterLevelUp.Status.PENDING,
        )

    def get_success_url(self) -> str:
        return self.character.get_absolute_url()

    def form_valid(self, form):
        resp = super().form_valid(form)
        form.instance.complete()
        return resp


character_level_up_complete_view = CharacterLevelUpCompleteView.as_view()

task_overflow/encounters/views.py
from typing import TYPE_CHECKING

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.query import QuerySet
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.views.generic.detail import DetailView

from task_overflow.hx.mixins import HXLoginRequiredMixin
from task_overflow.hx.triggers import CHARACTER_DETAILS_CHANGED
from task_overflow.hx.utils import htmx_trigger

from .models import Encounter

if TYPE_CHECKING:
    from task_overflow.monsters.models import Monster


class EncounterDetailView(LoginRequiredMixin, DetailView):
    model = Encounter

    def get_queryset(self) -> QuerySet["Encounter"]:
        return self.request.user.encounters()


encounter_detail_view = EncounterDetailView.as_view()


class EncounterHXAttackMonsterView(HXLoginRequiredMixin, DetailView):
    model = Encounter
    template_name = "encounters/includes/encounter_details.html"

    def monster(self) -> "Monster":
        return get_object_or_404(
            self.object.monster_set.all(),
            pk=self.kwargs["monster"],
        )

    def get_queryset(self) -> QuerySet["Encounter"]:
        return self.request.user.encounters()

    def get(self, *args, **kwargs):
        resp = super().get(*args, **kwargs)
        self.object.handle_attack(
            monster=self.monster(),
        )
        return htmx_trigger(CHARACTER_DETAILS_CHANGED, response=resp)


encounter_hx_attack_monster_view = EncounterHXAttackMonsterView.as_view()


@login_required()
def encounter_complete_view(request, pk: int):
    encounter = get_object_or_404(request.user.encounters(), pk=pk)
    encounter.complete()
    return redirect(encounter.character().get_absolute_url())

task_overflow/hx/views.py
from django.http import HttpResponse


def empty_view(request):
    return HttpResponse()

task_overflow/items/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.query import QuerySet
from django.shortcuts import get_object_or_404
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView

from task_overflow.mixins import CharacterRelatedDataViewMixin
from task_overflow.mixins import DefaultFormViewMixin

from .models import CharacterItem
from .models import Item


class CharacterItemCreateView(
    LoginRequiredMixin,
    DefaultFormViewMixin,
    CharacterRelatedDataViewMixin,
    CreateView,
):
    model = CharacterItem
    fields = [
        "quantity",
    ]
    form_header = "Purchase Item"
    redirect_to_character_on_success = True
    form_instance_assignments = {"character": "character"}

    def item(self) -> "Item":
        return get_object_or_404(Item.objects.all(), pk=self.kwargs["item"])

    @property
    def form_message(self) -> str:
        item = self.item()
        creds = self.character().credits
        return f"{item.name}, {item.base_price} ({creds} cryptobucks)"

    @property
    def cancel_path(self) -> str:
        return self.character().get_absolute_url()

    def get(self, *args, **kwargs):
        # Check if item pk is valid.
        self.item()
        return super().get(*args, **kwargs)

    def form_valid(self, form):
        item = self.item()
        if self.character().credits < (item.base_price * form.cleaned_data["quantity"]):
            form.add_error(
                "quantity",
                CharacterItem.CANNOT_AFFORD_PURCHASE_ERROR_MESSAGE,
            )
            return super().form_invalid(form)
        form.instance.item_id = item.pk
        resp = super().form_valid(form)
        self.character().credits -= item.base_price * form.instance.quantity
        self.character().save()
        return resp


character_item_create_view = CharacterItemCreateView.as_view()


class CharacterItemEquipMeleeWeaponView(
    LoginRequiredMixin,
    DefaultFormViewMixin,
    CharacterRelatedDataViewMixin,
    UpdateView,
):
    model = CharacterItem
    fields = []
    form_header = "Equip Item"
    redirect_to_character_on_success = True

    def item(self) -> "Item":
        return self.object.item

    @property
    def form_message(self) -> str:
        return f"Are you sure you want to equip {self.item().name}?"

    def get_queryset(self) -> QuerySet["CharacterItem"]:
        return self.request.user.character_items().filter(
            item__in=Item.objects.melee_weapons(),
        )

    def form_valid(self, form):
        resp = super().form_valid(form)
        self.character().melee_weapons().update(is_equipped=False)
        form.instance.is_equipped = True
        form.instance.save()
        return resp


character_item_equip_melee_weapon_view = CharacterItemEquipMeleeWeaponView.as_view()


class CharacterItemUseView(
    LoginRequiredMixin,
    DefaultFormViewMixin,
    CharacterRelatedDataViewMixin,
    UpdateView,
):
    model = CharacterItem
    fields = []
    form_header = "Use Item"
    redirect_to_character_on_success = True

    def item(self) -> "Item":
        return self.object.item

    @property
    def form_message(self) -> str:
        return f"Are you sure you want to use {self.item().name}?"

    def get_queryset(self) -> QuerySet["CharacterItem"]:
        return self.request.user.character_items().filter(quantity__gte=1)

    def form_valid(self, form):
        resp = super().form_valid(form)
        form.instance.use()
        return resp


character_item_use_view = CharacterItemUseView.as_view()

task_overflow/pages/views.py
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse


def home_view(request):
    if request.user.is_authenticated:
        if request.user.character_set.exists():
            character = request.user.character_set.first()
            return redirect(
                reverse(
                    "characters:detail",
                    kwargs={
                        "pk": character.pk,
                    },
                ),
            )
        return redirect(
            reverse("characters:create"),
        )
    return render(request, "pages/home.html")

task_overflow/users/api/views.py
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin
from rest_framework.mixins import RetrieveModelMixin
from rest_framework.mixins import UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from task_overflow.users.models import User

from .serializers import UserSerializer


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "pk"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

task_overflow/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}
  Forbidden (403)
{% endblock title %}
{% block content %}
  <h1>Forbidden (403)</h1>
  <p>
    {% if exception %}
      {{ exception }}
    {% else %}
      You're not allowed to access this page.
    {% endif %}
  </p>
{% endblock content %}

task_overflow/templates/base.html
{% load static i18n pipeline %}

<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>
      {% block title %}
        task overflow
      {% endblock title %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Cyberpunk-themed todo app and RPG" />
    <meta name="author" content="pcs108" />
    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}" />
    {% block css %}
      <!-- Latest compiled and minified Bootstrap CSS -->
      <link rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/css/bootstrap.min.css"
            integrity="sha512-SbiR/eusphKoMVVXysTKG/7VseWii+Y3FdHrt0EpKgpToZeemhqHeZeLWLhJutz/2ut2Vw1uQEj2MbRF+TVBUA=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer" />
      <!-- Your stuff: Third-party CSS libraries go here -->
      <script src="https://kit.fontawesome.com/50981ce29e.js"
              crossorigin="anonymous"></script>
      <script defer src="https://unpkg.com/htmx.org@2.0.2"></script>
      <!-- This file stores project-specific CSS -->
      {% stylesheet 'css_files' %}
    {% endblock css %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}
      <!-- Bootstrap JS -->
      <script defer
              src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/js/bootstrap.min.js"
              integrity="sha512-1/RvZTcCDEUjY/CypiMz+iqqtaoQfAITmNSJY17Myp4Ms5mdxPS5UV7iOfdZoxcGhzFbOm6sntTKJppjvuhg4g=="
              crossorigin="anonymous"
              referrerpolicy="no-referrer"></script>
      <!-- Your stuff: Third-party javascript libraries go here -->
      <!-- place project specific Javascript in this file -->
      {% javascript 'js_files' %}
    {% endblock javascript %}
  </head>
  <body class="{% block bodyclass %}bg-dark{% endblock bodyclass %}">
    {% block body %}
      <div class="mb-1">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
          <div class="container-fluid">
            <button class="navbar-toggler navbar-toggler-right"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="{% url 'pages:home' %}">task overflow</a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'pages:home' %}">Home <span class="visually-hidden">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'pages:about' %}">About</a>
                </li>
                {% if request.user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:detail' request.user.pk %}">{% translate "My Profile" %}</a>
                  </li>
                  <li class="nav-item">
                    {# URL provided by django-allauth/account/urls.py #}
                    <a class="nav-link" href="{% url 'account_logout' %}">{% translate "Sign Out" %}</a>
                  </li>
                {% else %}
                  {% if ACCOUNT_ALLOW_REGISTRATION %}
                    <li class="nav-item">
                      {# URL provided by django-allauth/account/urls.py #}
                      <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% translate "Sign Up" %}</a>
                    </li>
                  {% endif %}
                  <li class="nav-item">
                    {# URL provided by django-allauth/account/urls.py #}
                    <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% translate "Sign In" %}</a>
                  </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </nav>
      </div>
      <div class="container">
        {% include 'includes/messages.html' with messages=messages %}
        {% block main %}
          {% block content %}
            <p>Use this document as a way to quick start any new project.</p>
          {% endblock content %}
        {% endblock main %}
      </div>
    {% endblock body %}
    <!-- /container -->
    {% block modal %}
    {% endblock modal %}
    {% block inline_javascript %}
      <script>
        document.body.addEventListener('htmx:configRequest', (event) => {
          event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
        })
      </script>
    {% endblock inline_javascript %}
  </body>
</html>

task_overflow/templates/default_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
  <div class="default-form-container">
    <h1>{{ form_header|default:"Form" }}</h1>
    {{ form_message }}
    <form class="form-horizontal" method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <div class="control-group">
        <div class="controls">
          <button type="submit" class="btn btn-primary">Save</button>
          {% if cancel_path %}<a class="btn btn-danger" href="{{ cancel_path }}">Cancel</a>{% endif %}
        </div>
      </div>
    </form>
  </div>
{% endblock content %}