config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from drf_spectacular.views import SpectacularAPIView
from drf_spectacular.views import SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", include("task_overflow.pages.urls", namespace="pages")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("task_overflow.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path(
        "characters/", include("task_overflow.characters.urls", namespace="characters")
    ),
    path(
        "encounters/", include("task_overflow.encounters.urls", namespace="encounters")
    ),
    path(
        "hx/",
        include("task_overflow.hx.urls", namespace="hx"),
    ),
    path("items/", include("task_overflow.items.urls", namespace="items")),
    path(
        "tasks/",
        include("task_overflow.tasks.urls", namespace="tasks"),
    ),
    path(
        "trackers/",
        include("task_overflow.trackers.urls", namespace="trackers"),
    ),
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("api/auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

task_overflow/hx/urls.py
from django.urls import path

from .views import empty_view

app_name = "hx"
urlpatterns = [
    path("empty/", empty_view, name="empty"),
]

task_overflow/items/urls.py
from django.urls import path

from .views import character_item_create_view
from .views import character_item_equip_melee_weapon_view
from .views import character_item_use_view

app_name = "items"
urlpatterns = [
    path(
        "<int:character>/character-items/<int:item>/~create/",
        view=character_item_create_view,
        name="character-item-create",
    ),
    path(
        "character-items/melee-weapons/<int:pk>/~equip/",
        view=character_item_equip_melee_weapon_view,
        name="character-melee-weapon-equip",
    ),
    path(
        "character-items/<int:pk>/~use/",
        view=character_item_use_view,
        name="character-item-use",
    ),
]

task_overflow/pages/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import home_view

app_name = "pages"
urlpatterns = [
    path("", home_view, name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
]

task_overflow/tasks/urls.py
from django.urls import path

from .views import category_create_view
from .views import category_detail_view
from .views import habit_create_view
from .views import habit_delete_view
from .views import habit_do_view
from .views import habit_update_view
from .views import todo_hx_complete_view
from .views import todo_hx_create_view
from .views import todo_hx_delete_view
from .views import todo_hx_due_today_view
from .views import todo_hx_fail_view
from .views import todo_hx_list_item_view
from .views import todo_hx_list_view
from .views import todo_hx_notes_hide_view
from .views import todo_hx_notes_show_view
from .views import todo_hx_update_view

app_name = "tasks"
urlpatterns = [
    path(
        "<int:character>/categories/~create/",
        view=category_create_view,
        name="character-category-create",
    ),
    path(
        "categories/<int:pk>/",
        view=category_detail_view,
        name="category-detail",
    ),
    path(
        "<int:character>/habits/~create/",
        view=habit_create_view,
        name="character-habit-create",
    ),
    path("habits/<int:pk>/~update/", view=habit_update_view, name="habit-update"),
    path("habits/<int:pk>/~delete/", view=habit_delete_view, name="habit-delete"),
    path("habits/<int:pk>/~do/", view=habit_do_view, name="habit-do"),
    path(
        "hx/<int:character>/todos/~create/",
        view=todo_hx_create_view,
        name="character-todo-hx-create",
    ),
    path(
        "hx/<int:character>/todos/",
        view=todo_hx_list_view,
        name="character-todo-hx-list",
    ),
    path(
        "hx/todos/<int:pk>/",
        view=todo_hx_list_item_view,
        name="todo-hx-list-item",
    ),
    path(
        "hx/todos/<int:pk>/notes/~hide/",
        view=todo_hx_notes_hide_view,
        name="todo-hx-notes-hide",
    ),
    path(
        "hx/todos/<int:pk>/notes/~show/",
        view=todo_hx_notes_show_view,
        name="todo-hx-notes-show",
    ),
    path(
        "hx/todos/<int:pk>/~update/",
        view=todo_hx_update_view,
        name="todo-hx-update",
    ),
    path(
        "hx/todos/<int:pk>/~complete/",
        view=todo_hx_complete_view,
        name="todo-hx-complete",
    ),
    path(
        "hx/todos/<int:pk>/~fail/",
        view=todo_hx_fail_view,
        name="todo-hx-fail",
    ),
    path(
        "hx/todos/<int:pk>/~due-today/",
        view=todo_hx_due_today_view,
        name="todo-hx-due-today",
    ),
    path(
        "hx/todos/<int:pk>/~delete/",
        view=todo_hx_delete_view,
        name="todo-hx-delete",
    ),
]

task_overflow/hx/models.py
# Create your models here.

task_overflow/trackers/forms.py
from django import forms

from .models import Adjustment


class NegativeAdjustmentForm(forms.ModelForm):
    def clean_value(self):
        return self.cleaned_data["value"] * -1

    class Meta:
        model = Adjustment
        fields = ["value"]

task_overflow/characters/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.urls import reverse
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView

from task_overflow.hx.decorators import hx_login_required
from task_overflow.hx.mixins import HXLoginRequiredMixin
from task_overflow.hx.utils import htmx_redirect
from task_overflow.items.models import Item
from task_overflow.utils import empty_response

from .models import Character
from .models import CharacterLevelUp
from .models import CharacterMessage


def display_message(request, message: "CharacterMessage") -> None:
    messages.add_message(
        request,
        level=message.level,
        message=message.text,
    )
    message.status = CharacterMessage.Status.VIEWED
    message.save()


class CharacterCreateView(LoginRequiredMixin, CreateView):
    model = Character
    fields = [
        "name",
        "avatar",
    ]
    success_message = "Character created"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


character_create_view = CharacterCreateView.as_view()


class CharacterDetailView(LoginRequiredMixin, DetailView):
    model = Character

    def get_queryset(self):
        return self.request.user.character_set.all()

    def get_object(self, *args, **kwargs) -> "Character":
        obj = super().get_object(*args, **kwargs)
        for death in obj.pending_deaths():
            death.die()
        for message in obj.ordered_pending_messages():
            display_message(self.request, message=message)
        return obj

    def get_context_data(self, *args, **kwargs) -> dict:
        context = super().get_context_data(*args, **kwargs)
        context["items_for_sale"] = Item.objects.for_sale()
        return context


character_detail_view = CharacterDetailView.as_view()


@hx_login_required
def character_hx_fetch_messages_view(request, pk: int):
    character = get_object_or_404(request.user.character_set, pk=pk)
    for message in character.ordered_pending_messages():
        display_message(request, message=message)
    return render(request, "includes/messages.html")


@hx_login_required
def character_hx_check_for_active_encounter_view(request, pk: int, force: int = 0):
    force = force == 1
    character = get_object_or_404(request.user.character_set, pk=pk)
    active_encounter = character.get_or_create_active_encounter(force=force)
    if active_encounter:
        messages.add_message(
            request,
            message="You were attacked!",
            level=messages.ERROR,
        )
        return htmx_redirect(
            for_path=reverse(
                "encounters:detail",
                kwargs={
                    "pk": active_encounter.pk,
                },
            ),
        )
    return empty_response()


class CharacterHXFetchDetailsView(HXLoginRequiredMixin, DetailView):
    model = Character
    template_name = "characters/includes/character_details.html"

    def get_queryset(self):
        return self.request.user.character_set.all()

    def get_object(self, *args, **kwargs) -> "Character":
        obj = super().get_object(*args, **kwargs)
        for death in obj.pending_deaths():
            death.die()
        return obj


character_hx_fetch_details_view = CharacterHXFetchDetailsView.as_view()


class CharacterUpdateView(LoginRequiredMixin, UpdateView):
    model = Character
    fields = [
        "name",
        "avatar",
    ]
    success_message = "Character updated"

    def get_queryset(self):
        return self.request.user.character_set.all()


character_update_view = CharacterUpdateView.as_view()


class CharacterLevelUpCompleteView(LoginRequiredMixin, UpdateView):
    model = CharacterLevelUp
    fields = [
        "hit_points",
        "strength_points",
        "dexterity_points",
        "initiative_points",
    ]

    @property
    def character(self) -> "Character":
        return self.object.character

    def get_queryset(self):
        return self.request.user.character_level_ups().filter(
            status=CharacterLevelUp.Status.PENDING,
        )

    def get_success_url(self) -> str:
        return self.character.get_absolute_url()

    def form_valid(self, form):
        resp = super().form_valid(form)
        form.instance.complete()
        return resp


character_level_up_complete_view = CharacterLevelUpCompleteView.as_view()

task_overflow/encounters/views.py
from typing import TYPE_CHECKING

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.query import QuerySet
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.views.generic.detail import DetailView

from task_overflow.hx.mixins import HXLoginRequiredMixin
from task_overflow.hx.triggers import CHARACTER_DETAILS_CHANGED
from task_overflow.hx.utils import htmx_trigger

from .models import Encounter

if TYPE_CHECKING:
    from task_overflow.monsters.models import Monster


class EncounterDetailView(LoginRequiredMixin, DetailView):
    model = Encounter

    def get_queryset(self) -> QuerySet["Encounter"]:
        return self.request.user.encounters()


encounter_detail_view = EncounterDetailView.as_view()


class EncounterHXAttackMonsterView(HXLoginRequiredMixin, DetailView):
    model = Encounter
    template_name = "encounters/includes/encounter_details.html"

    def monster(self) -> "Monster":
        return get_object_or_404(
            self.object.monster_set.all(),
            pk=self.kwargs["monster"],
        )

    def get_queryset(self) -> QuerySet["Encounter"]:
        return self.request.user.encounters()

    def get(self, *args, **kwargs):
        resp = super().get(*args, **kwargs)
        self.object.handle_attack(
            monster=self.monster(),
        )
        return htmx_trigger(CHARACTER_DETAILS_CHANGED, response=resp)


encounter_hx_attack_monster_view = EncounterHXAttackMonsterView.as_view()


@login_required()
def encounter_complete_view(request, pk: int):
    encounter = get_object_or_404(request.user.encounters(), pk=pk)
    encounter.complete()
    return redirect(encounter.character().get_absolute_url())

task_overflow/hx/views.py
from django.http import HttpResponse


def empty_view(request):
    return HttpResponse()

task_overflow/items/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.query import QuerySet
from django.shortcuts import get_object_or_404
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView

from task_overflow.mixins import CharacterRelatedDataViewMixin
from task_overflow.mixins import DefaultFormViewMixin

from .models import CharacterItem
from .models import Item


class CharacterItemCreateView(
    LoginRequiredMixin,
    DefaultFormViewMixin,
    CharacterRelatedDataViewMixin,
    CreateView,
):
    model = CharacterItem
    fields = [
        "quantity",
    ]
    form_header = "Purchase Item"
    redirect_to_character_on_success = True
    form_instance_assignments = {"character": "character"}

    def item(self) -> "Item":
        return get_object_or_404(Item.objects.all(), pk=self.kwargs["item"])

    @property
    def form_message(self) -> str:
        item = self.item()
        creds = self.character().credits
        return f"{item.name}, {item.base_price} ({creds} cryptobucks)"

    @property
    def cancel_path(self) -> str:
        return self.character().get_absolute_url()

    def get(self, *args, **kwargs):
        # Check if item pk is valid.
        self.item()
        return super().get(*args, **kwargs)

    def form_valid(self, form):
        item = self.item()
        if self.character().credits < (item.base_price * form.cleaned_data["quantity"]):
            form.add_error(
                "quantity",
                CharacterItem.CANNOT_AFFORD_PURCHASE_ERROR_MESSAGE,
            )
            return super().form_invalid(form)
        form.instance.item_id = item.pk
        resp = super().form_valid(form)
        self.character().credits -= item.base_price * form.instance.quantity
        self.character().save()
        return resp


character_item_create_view = CharacterItemCreateView.as_view()


class CharacterItemEquipMeleeWeaponView(
    LoginRequiredMixin,
    DefaultFormViewMixin,
    CharacterRelatedDataViewMixin,
    UpdateView,
):
    model = CharacterItem
    fields = []
    form_header = "Equip Item"
    redirect_to_character_on_success = True

    def item(self) -> "Item":
        return self.object.item

    @property
    def form_message(self) -> str:
        return f"Are you sure you want to equip {self.item().name}?"

    def get_queryset(self) -> QuerySet["CharacterItem"]:
        return self.request.user.character_items().filter(
            item__in=Item.objects.melee_weapons(),
        )

    def form_valid(self, form):
        resp = super().form_valid(form)
        self.character().melee_weapons().update(is_equipped=False)
        form.instance.is_equipped = True
        form.instance.save()
        return resp


character_item_equip_melee_weapon_view = CharacterItemEquipMeleeWeaponView.as_view()


class CharacterItemUseView(
    LoginRequiredMixin,
    DefaultFormViewMixin,
    CharacterRelatedDataViewMixin,
    UpdateView,
):
    model = CharacterItem
    fields = []
    form_header = "Use Item"
    redirect_to_character_on_success = True

    def item(self) -> "Item":
        return self.object.item

    @property
    def form_message(self) -> str:
        return f"Are you sure you want to use {self.item().name}?"

    def get_queryset(self) -> QuerySet["CharacterItem"]:
        return self.request.user.character_items().filter(quantity__gte=1)

    def form_valid(self, form):
        resp = super().form_valid(form)
        form.instance.use()
        return resp


character_item_use_view = CharacterItemUseView.as_view()

task_overflow/pages/views.py
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse


def home_view(request):
    if request.user.is_authenticated:
        if request.user.character_set.exists():
            character = request.user.character_set.first()
            return redirect(
                reverse(
                    "characters:detail",
                    kwargs={
                        "pk": character.pk,
                    },
                ),
            )
        return redirect(
            reverse("characters:create"),
        )
    return render(request, "pages/home.html")

task_overflow/templates/tasks/includes/category_list.html
<ul class="info-list">
  {% for category in categories %}
    <li>
      <a href="{% url 'tasks:category-detail' pk=category.pk %}">{{ category.name }} [{{ category.priority }}]</a>
    </li>
  {% endfor %}
</ul>

task_overflow/templates/tasks/includes/habit_list.html
<ul class="object-list">
  {% for habit in uncompleted_habits %}
    <li>
      <div class="object-list-item-section">
        <a href="{% url 'tasks:habit-do' pk=habit.pk %}"><i class="object-list-item-action fa-solid fa-arrow-up fa-lg"></i></a>
        [{{ habit.streak }}] {{ habit.category.name }} <b>{{ habit.name }}</b> ({{ habit.experience_points }} points)
      </div>
      <div class="object-list-item-section object-list-item-actions-bar">
        <a href="{% url 'tasks:habit-update' pk=habit.pk %}"><i class="object-list-item-action fa-solid fa-pen"></i></a>
        <a href="{% url 'tasks:habit-delete' pk=habit.pk %}"><i class="object-list-item-action fa-solid fa-trash-can"></i></a>
      </div>
    </li>
  {% endfor %}
  {% for completed in completed_habits %}
    <li>
      <div class="object-liste-item-section">
        [{{ completed.streak }}] {{ completed.category.name }} {{ completed.name }}
      </div>
    </li>
  {% endfor %}
</ul>

task_overflow/templates/tasks/includes/todo_list.html
{% load url_with_todo_filters %}
{% load filter_style %}

<div id="todosContainer">
  <h2>Todo List</h2>
  <a hx-get="{% url_with_todo_filters 'tasks:character-todo-hx-list' character=character.pk f='pending' %}"
     hx-target="#todosContainer"
     hx-swap="outerHTML">
    <i class="{% filter_style f='pending' %} object-list-filter fa-solid fa-bolt fa-lg"></i>
  </a>
  <a hx-get="{% url_with_todo_filters 'tasks:character-todo-hx-list' character=character.pk f='backlog' %}"
     hx-target="#todosContainer"
     hx-swap="outerHTML">
    <i class="{% filter_style f='backlog' %} object-list-filter fa-solid fa-calendar fa-lg"></i>
  </a>
  {% for category in character.ordered_categories %}
    <a hx-get="{% url_with_todo_filters 'tasks:character-todo-hx-list' character=character.pk c=category.name %}"
       hx-target="#todosContainer"
       hx-swap="outerHTML">
      <span class="{% filter_style c=category.name %}">{{ category.name }}</span>
    </a>
  {% endfor %}
  <a hx-get="{% url_with_todo_filters 'tasks:character-todo-hx-create' character=character.pk %}"
     hx-target="#todoList"
     hx-swap="afterbegin"><i class="fa-solid fa-plus"></i></a>
  <ul id="todoList" class="object-list">
    {% for todo in todo_list %}
      {% include "tasks/includes/todo_list_item.html" with todo=todo %}
    {% empty %}
      <div id="emptyTodos"
           hx-get="{% url 'hx:empty' %}"
           hx-swap="outerHTML"
           hx-trigger="{{ TODO_ADDED }} from:body">
        No todos.
      </li>
    {% endfor %}
  </ul>
</div>

task_overflow/templates/tasks/includes/todo_list_form.html
{% load crispy_forms_tags %}

<li id="{{ hx_target_id }}">
  <h1>{{ form_header|default:"Form" }}</h1>
  {{ form_message }}
  <form class="form-horizontal"
        hx-post="{{ hx_post }}"
        hx-target="#{{ hx_target_id }}"
        hx-swap="outerHTML">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Save</button>
        <a class="btn btn-danger"
           hx-get="{{ cancel_path }}"
           hx-target="#{{ hx_target_id }}"
           hx-swap="outerHTML">Cancel</a>
      </div>
    </div>
  </form>
</li>

task_overflow/templates/tasks/includes/todo_list_item.html
{% load todo_style %}

<li id="todo-{{ todo.pk }}">
  <div class="object-list-item-section">
    <a hx-post="{% url 'tasks:todo-hx-complete' pk=todo.pk %}"
       hx-target="#todo-{{ todo.pk }}"
       hx-swap="outerHTML"><i class="object-list-item-action fa-solid fa-check fa-xl"></i></a>
    <b><span class="{{ todo|todo_style }}">{{ todo.category.name }} {{ todo.name }}</span></b> {{ todo.due_date|date:"D M j"|default:"" }} ({{ todo.experience_points }} points)
    {% if todo.recurring_schedule %}<i class="fa-solid fa-repeat fa-lg"></i>{% endif %}
    <a hx-get="{% url 'hx:empty' %}"
       hx-target="#todo-{{ todo.pk }}"
       hx-swap="outerHTML"><i class="object-list-item-action fa-solid fa-minus fa-xl"></i></a>
  </div>
  {% if todo.notes %}
    {% include "tasks/includes/todo_notes_hide.html" with todo=todo %}
  {% endif %}
  <div class="object-list-item-section object-list-item-actions-bar">
    <a hx-post="{% url 'tasks:todo-hx-fail' pk=todo.pk %}"
       hx-target="#todo-{{ todo.pk }}"
       hx-swap="outerHTML"><i class="object-list-item-action fa-solid fa-x fa-xl"></i></a>
    <a hx-post="{% url 'tasks:todo-hx-due-today' pk=todo.pk %}"
       hx-target="#todo-{{ todo.pk }}"
       hx-swap="outerHTML"><i class="object-list-item-action fa-regular fa-clock fa-xl"></i></a>
    <a hx-get="{% url 'tasks:todo-hx-update' pk=todo.pk %}"
       hx-target="#todo-{{ todo.pk }}"
       hx-swap="outerHTML"><i class="object-list-item-action fa-solid fa-pen"></i></a>
    <a hx-post="{% url 'tasks:todo-hx-delete' pk=todo.pk %}"
       hx-target="#todo-{{ todo.pk }}"
       hx-swap="outerHTML"><i class="object-list-item-action fa-solid fa-trash-can"></i></a>
  </div>
</li>

task_overflow/templates/tasks/includes/todo_notes_hide.html
<div id="notes{{ todo.pk }}Notes" class="object-list-item-section">
  <i hx-get="{% url 'tasks:todo-hx-notes-show' pk=todo.pk %}"
     hx-target="#notes{{ todo.pk }}Notes"
     hx-swap="outerHTML"
     class="notes-toggle fa-regular fa-file-lines"></i>
</div>

task_overflow/templates/tasks/includes/todo_notes_show.html
<div id="notes{{ todo.pk }}Notes" class="object-list-item-section">
  <i hx-get="{% url 'tasks:todo-hx-notes-hide' pk=todo.pk %}"
     hx-target="#notes{{ todo.pk }}Notes"
     hx-swap="outerHTML"
     class="notes-toggle fa-regular fa-file-lines"></i>
  {{ todo.notes }}
</div>